#!/usr/bin/env bash
set -euo pipefail

admits=$(grep -RIn --include="*.v" '\bAdmitted\.' modules/IEL/ | grep -v '\(\*.*TODO.*\)\|\(\*.*remove.*Admitted\)' | wc -l | xargs)
loadp=$(grep -RIn --include="*.v" '\bAdd[[:space:]]+LoadPath\b' modules/IEL/ | wc -l | xargs)
ts="$(date -u +'%Y-%m-%d %H:%M:%S UTC')"

echo "# IEL Build Status"
echo
echo "- Timestamp: ${ts}"
echo "- Admitted occurrences: ${admits}"
echo "- Add LoadPath occurrences: ${loadp}"
echo
if [[ "${admits}" -eq 0 && "${loadp}" -eq 0 ]]; then
  echo "✅ **Policy clean.**"
else
  echo "❌ **Policy violations present.**"
  [[ "${admits}" -ne 0 ]] && echo "  - Remove Admitted. from proofs."
  [[ "${loadp}" -ne 0 ]] && echo "  - Replace Add LoadPath with -Q in _CoqProject."
fi
echo
echo "## Checklist"
echo "- [$( [[ ${admits} -eq 0 ]] && echo x || echo ' ' )] No \`Admitted.\` under \`modules/IEL\`"
echo "- [$( [[ ${loadp} -eq 0 ]] && echo x || echo ' ' )] No \`Add LoadPath\` under \`modules/IEL\`"
echo "- [x] Build via Bash make"
echo
echo "## Notes"
echo "Generated by scripts/gen_status.sh."