# services/oracle_ui/Dockerfile
FROM python:3.10-slim

WORKDIR /app

# Install system dependencies needed for audio processing
RUN apt-get update && apt-get install -y ffmpeg

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./services/oracle_ui /app

EXPOSE 7860

CMD ["python", "oracle_app.py"]