defaults:
  conservativity: true
  zero_admits: true

subsystems:
  Thonoc: { preferred: [GnosiPraxis], fallbacks: [TropoPraxis] }
  Tetranose: { preferred: [DynaPraxis, ErgoPraxis, MuPraxis], fallbacks: [TropoPraxis] }
  Telos: { preferred: [TeloPraxis, ThemiPraxis, TychePraxis], fallbacks: [TropoPraxis, GnosiPraxis] }
  Archon: { preferred: [HexiPraxis, Axiopraxis, ChremaPraxis], fallbacks: [GnosiPraxis, ThemiPraxis] }
  Cosmos: { preferred: [CosmoPraxis, ChronoPraxis, TopoPraxis], fallbacks: [TropoPraxis] }
  Anthro: { preferred: [AnthroPraxis], fallbacks: [GnosiPraxis, ThemiPraxis], subdomains: [BioPraxis] }

routing:
  ontology: OntoPraxis
  epistemology: GnosiPraxis
  axiology: Axiopraxis
  praxeology: ErgoPraxis
  anthropology: AnthroPraxis
  teleology: TeloPraxis
  cosmology: CosmoPraxis
  spatial: TopoPraxis
  theology: PXL-Core
