name: deploy-helm
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${KUBECONFIG_B64}" | base64 -d > ~/.kube/config
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}
      - name: Deploy
        run: |
          helm upgrade --install logos charts/logos \
            --namespace ${NAMESPACE:-logos} --create-namespace \
            --set global.imageRegistry=ghcr.io/${{ github.repository_owner }} \
            --set toolRouter.tag=sha-${GITHUB_SHA} \
            --set logosApi.tag=sha-${GITHUB_SHA} \
            --set interactiveChat.tag=sha-${GITHUB_SHA} \
            --set global.signingSecret="${SIGNING_SECRET}" \
            --set global.apiSigningSecret="${API_SIGNING_SECRET}" \
            --set global.useRedisLimiter=${USE_REDIS_LIMITER:-false}
        env:
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
          API_SIGNING_SECRET: ${{ secrets.API_SIGNING_SECRET }}
          USE_REDIS_LIMITER: ${{ secrets.USE_REDIS_LIMITER }}
          NAMESPACE: ${{ secrets.K8S_NAMESPACE }}