version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3.9-management-alpine"
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI

  keryx_api:
    build: ./services/keryx_api
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - rabbitmq

  # --- NEW ORACLE UI SERVICE ---
  oracle_ui:
    build: ./services/oracle_ui  # <-- CORRECTION: Point build context to the service directory
    ports:
      - "7860:7860"
    environment:
      - KERYX_API_URL=http://keryx_api:5000
    depends_on:
      - keryx_api

  database:
    build: ./services/database
    volumes:
      - db_data:/data
    env_file: .env
    depends_on:
      - rabbitmq

  logos_nexus:
    build: ./services/logos_nexus
    env_file: .env
    volumes:
      - ./config:/app/config:ro
    depends_on:
      - rabbitmq

  archon_nexus:
    build: ./services/archon_nexus
    env_file: .env
    volumes:
      - ./config:/app/config:ro
      - ./external_libraries:/app/external_libraries:ro
    environment:
      - PYTHONPATH=/app:/app/external_libraries/networkx-main
    depends_on:
      - rabbitmq

  tetragnos:
    build: ./subsystems/tetragnos
    env_file: .env
    volumes:
      - ./external_libraries:/app/external_libraries:ro
    environment:
      - PYTHONPATH=/app:/app/external_libraries/pytorch-main:/app/external_libraries/sentence-transformers-master
    depends_on:
      - rabbitmq

  thonoc:
    build: ./subsystems/thonoc
    env_file: .env
    volumes:
      - ./config:/app/config:ro
      - ./external_libraries:/app/external_libraries:ro
    environment:
      - PYTHONPATH=/app:/app/external_libraries/sympy-master # Example, adjust as needed
    depends_on:
      - rabbitmq

  telos:
    build: ./subsystems/telos
    env_file: .env
    volumes:
      - ./config:/app/config:ro
      - ./external_libraries:/app/external_libraries:ro
    environment:
      - PYTHONPATH=/app:/app/external_libraries/pymc-main:/app/external_libraries/arch-main:/app/external_libraries/filterpy-master:/app/external_libraries/pmdarima-master:/app/external_libraries/pykalman-main
    depends_on:
      - rabbitmq

volumes:
  db_data:
